### ISSUE TITLE
ModuleNotFoundError: No module named 'xgboost'

### ISSUE THREAD

**Issue by varunsach** [shankarpandala/lazypredict#171]
![Capture](https://user-images.githubusercontent.com/48254967/91882641-e76fae80-eca0-11ea-864d-ff5e7df9bd91.GIF)
@shankarpandala : i really liked this library and will help in future, reporting a bug / issue

**Describe the bug**
I have literally copy pasted the entire code in Jupyter notebook. I am getting an error 

**ModuleNotFoundError: No module named 'xgboost'**

**Expected behavior**

**Screenshots**
I am attaching screenshot for your reference

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by shankarpandala** [comment]
Please install xgboost and lightgbm with pip

**Comment by varunsach** [comment]
Thanks, that helps. I thought it will automatically install dependencies.

It now gives a error AttributeError: module 'sklearn.ensemble' has no attribute '_hist_gradient_boosting'

**Comment by shankarpandala** [comment]
Hope you are using latest version?
For this error install latest version of scikit-learn

**Comment by varunsach** [comment]
@shankarpandala .. i updated packages and i think package issue is fixed... but next issue is as follows
it throws below error and stops after 84% processing
![Capture1](https://user-images.githubusercontent.com/48254967/91889391-64078a80-ecab-11ea-81b3-efeffbcc3e6e.GIF)

**Comment by shankarpandala** [comment]
change ignore_warnings to True

**Comment by varunsach** [comment]
@shankarpandala did that, still it shows the same error

**StackingRegressor model failed to execute
__init__() missing 1 required positional argument: 'estimators'**

![Capture2](https://user-images.githubusercontent.com/48254967/91890166-abdae180-ecac-11ea-8476-fb169d7fdd39.GIF)

**Comment by shankarpandala** [comment]
I can still see it as false in screenshot.
Change it to True

**Comment by shankarpandala** [comment]
It is completed. It shows 100%

Just type models in next cell to see the table

**Comment by varunsach** [comment]
@shankarpandala 
superb, it works now. I really appreciate your patience and response time. For novice like me you guys are blessing. All the best for your future, last but not the least, fantastic package to work with.
